Repository HanRiverMeetup/HanRiverMeetup-android, pull requests merged in 2018-07, with the labels that each got.

#19 develop click event to MeetingCategory
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/HanRiverMeetupApplication.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/activity/main/MainTabPagerAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/CreateRoomDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/IActivityDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/ICreateRoomDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/ExpandableListAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/MeetingCategoryAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/MeetingCategoryViewHolder.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/OnListItemClickListener.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCategoryFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCategoryViewModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCreateRoom.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingListFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/meetingRootFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/meeting/Room.java
  app/src/main/res/drawable/categoryitem_border.xml
  app/src/main/res/drawable/ic_chicken_icon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activitycategoryitem.xml
  app/src/main/res/layout/createroom_item.xml
  app/src/main/res/layout/fragment_meeting_category.xml
  app/src/main/res/layout/fragment_meeting_createroom.xml
  app/src/main/res/layout/fragment_meeting_list.xml
  app/src/main/res/layout/meetingroot.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#23 #22 서버와의 통신을 위한 API 호출 모듈 작성
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/ExpandableListAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/meeting/Comment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/meeting/JoinRequest.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/meeting/MatchingDetail.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/meeting/MeetingDetail.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/user/LoginInfo.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/APIUtiles.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/CommunicationService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/GuestService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/HostService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/LoginService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/RetrofitClient.java
Labels: enhancement

#27 #18 add mypage tab1 recyclerview
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/HanRiverMeetupApplication.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/mypage/IMyPageTab1DataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/mypage/MyPageTab1DataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/timeline/ITimelineDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/timeline/TimelineDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Adapter/Tab1Adapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Adapter/Tab2Adapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Adapter/Tab3Adapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Tab1.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/ViewModel/Tab1ViewModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/timeline/TimelineFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/timeline/TimelineViewModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/mypage/Tab1VO.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/mypage/Tab2VO.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/mypage/Tab3VO.java
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_timeline.xml
  app/src/main/res/layout/tab1_fragment.xml
  app/src/main/res/layout/tab_item.xml
Labels: enhancement

#29 #21 add facebook login activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/Activity/login/LoginActivity.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/Activity/main/MainActivity.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/activity/main/MainTabPagerAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/MeetingListInnerDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/login/LoginFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCategoryFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingListFragment.java
  app/src/main/res/drawable/back_grad_color.xml
  app/src/main/res/drawable/ic_bt_plus.xml
  app/src/main/res/drawable/ic_camping_icon.xml
  app/src/main/res/drawable/ic_camping_icon_white.xml
  app/src/main/res/drawable/ic_weather_sunny.xml
  app/src/main/res/layout/fragment_meeting_category.xml
  app/src/main/res/layout/fragment_meeting_list.xml
Labels: enhancement

#30 close #22 로그인을 위한 임시 페이지 구성
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/Activity/login/LoginActivity.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/Activity/main/MainActivity.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/HanRiverMeetupApplication.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/activity/main/MainTabPagerAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/login/CreateAccountFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/login/LoginFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCategoryFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingListFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/user/LoginInfo.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/user/User.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/APIUtiles.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/AuthenticationInterceptor.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/CommunicationAPIService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/GuestAPIService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/HostAPIService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/LoginAPIService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/LoginService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/RetrofitClient.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/service/LoginService.java
  app/src/main/res/drawable/ic_app_logo.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_create_account.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/login_page.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#36 close #35 로그인시 회원가입이 안되어있으면 회원 가입 할 수 있도록 기능 추가
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/login/CreateAccountFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/login/LoginFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/APIUtiles.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/AuthenticationInterceptor.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/LoginAPIService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/network/RetrofitClient.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/service/CommunicationService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/service/GuestService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/service/HostService.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/service/LoginService.java
  app/src/main/res/layout/fragment_create_account.xml
Labels: feature

#37 #32 add create meeting room view
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/activity/login/LoginActivity.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/activity/main/MainActivity.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/ActivityDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/Category/MeetingCategoryAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/CreateRoom/ExpandableListAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCreateRoom.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/meeting/Activity.java
  app/src/main/res/drawable/ic_bike_icon.xml
  app/src/main/res/drawable/ic_down_arrow.xml
  app/src/main/res/drawable/ic_etc_icon.xml
  app/src/main/res/drawable/ic_ori_icon.xml
  app/src/main/res/drawable/ic_photo_icon.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/invalid_name.png
  app/src/main/res/layout/createroom_item.xml
  app/src/main/res/layout/fragment_meeting_category.xml
  app/src/main/res/layout/fragment_meeting_createroom.xml
Labels: enhancement

#41 closed #38 add meeting detail view
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/HanRiverMeetupApplication.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/activity/main/MainTabPagerAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/IMeetingDetailDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/MeetingDetailDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/List/MeetingListAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/List/MeetingListTapPagerAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/List/MeetingListViewHolder.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/Adapter/List/OnListitemClickListener.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingDetailFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingDetailViewModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingListFragment.java
  app/src/main/res/drawable/textline.xml
  app/src/main/res/layout/detail_comment_item.xml
  app/src/main/res/layout/fragment_meeting_detail.xml
  app/src/main/res/layout/fragment_meeting_list.xml
  app/src/main/res/layout/fragment_meeting_list_inner.xml
  app/src/main/res/layout/meetingroot.xml
Labels: enhancement

#43 closed #40 MyPage 내가 만든 모임 탭의 신청자 리스트 구현
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Adapter/ApplicantListAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Adapter/Tab1Adapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/SelectionDialog.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/mypage/ApplicantVO.java
  app/src/main/res/layout/custom_tab1_layout.xml
  app/src/main/res/layout/custom_tab2_layout.xml
  app/src/main/res/layout/custom_tab3_layout.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/mypage_tab1_applicant_list_item.xml
  app/src/main/res/layout/mypage_tab1_item.xml
  app/src/main/res/layout/mypage_tab1_maked_room.xml
  app/src/main/res/layout/selection_dialog.xml
Labels: enhancement

#45 #44 add mypage tab2 applied meeting
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Adapter/Tab2Adapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/CustomViewpager.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/MyPageFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Tab2.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/mypage/Tab2VO.java
  app/src/main/res/drawable/ic_nagative_icon.xml
  app/src/main/res/drawable/ic_positive_icon.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/mypage_tab2_item.xml
  app/src/main/res/layout/selection_dialog.xml
  app/src/main/res/layout/tab2_fragment.xml
Labels: enhancement

#47 closed #46 add mypage tab3 finished meeting
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Adapter/Tab3Adapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/mypage/Tab3.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/mypage/Tab3VO.java
  app/src/main/res/drawable/ic_call_button.xml
  app/src/main/res/drawable/ic_location_button.png
  app/src/main/res/layout/mypage_tab3_item.xml
  app/src/main/res/layout/tab3_fragment.xml
Labels: enhancement
