Repository HanRiverMeetup/HanRiverMeetup-android, pull requests merged in 2018-06, with the labels that each got.

#5 #4 탭 레이아웃을 통한 탭 메뉴 구성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/Activity/main/MainActivity.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/HanRiverMeetupApplication.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/activity/main/MainTabPagerAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCategoryFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/meeting/MeetingCategoryViewModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/timeline/TimelineFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_meeting_category.xml
  app/src/main/res/layout/fragment_timeline.xml
  app/src/main/res/values/strings.xml
Labels: feature

#9 closed #8 테스트중
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/Activity/main/MainActivity.java
Labels: help wanted

#15 closed #13 recyclerview finished
  app/build.gradle
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/HanRiverMeetupApplication.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/ITimelineDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/datamodel/meeting/TimelineDataModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/timeline/Adapter/TimeLineAdapter.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/timeline/TimelineFragment.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/fragment/timeline/TimelineViewModel.java
  app/src/main/java/com/depromeet/hanriver/hanrivermeetup/model/timeline/TimeLineVO.java
  app/src/main/res/layout/fragment_timeline.xml
  app/src/main/res/layout/timeline_item.xml
Labels: enhancement
